export const application_routes = {
  MAIN_ROOT: 'bank',
  AUTH: 'auth',
  AUTH_PHONE_CODE: 'auth-otp',
  AUTH_PHONE_NUMBER: 'auth-phone-number',
  APP: 'bank',
  LAYOUT: 'layout',
  DASHBOARD: 'dashboard',
  TRANSACTIONS: 'transactions',
  ACCOUNTS: 'accounts',
  INVESTMENTS: 'investments',
  CREDIT_CARDS: 'credit-cards',
  LOANS: 'loans',
  SERVICES: 'services',
  MY_PRIVILAGES: 'my-privilages',
  SETTINGS: 'settings',
};
